### PR TITLE
bug: allow RFC5321 compliant email addresses

### LINKED ISSUE #44: Allow RFC5321 compliant email addresses
Looks like the code is doing very primitive email verification. We should at the very least allow '+' in the local part.

patch inbound.

### PR DESCRIPTION
**Pull request by jrconlin**
email address validation is a pain, and you can use a surprising variety
of characters in an address.

(At least we're drawing the line at no quoted characters...)

Closes #44

### CODE REVIEW

**Comment by philbooth** [comment]
Thanks @jrconlin!

File: src/validate/mod.rs [hunk 1]
```diff
@@ -15,7 +15,7 @@ lazy_static! {
         "^https?://[A-Za-z0-9-]+(?:\\.[A-Za-z0-9-]+)*(?::[0-9]+)?/(?:[A-Za-z0-9-]+/)*$"
     ).unwrap();
     static ref EMAIL_ADDRESS_FORMAT: Regex =
-        Regex::new("^[a-z0-9-]+@[a-z0-9-]+(?:\\.[a-z0-9-]+)+$").unwrap();
+        Regex::new("^[a-z0-9\\-!#\\$%\\&`\\*\\+/=\\?\\^{\\|}~]+@[a-z0-9-]+(?:\\.[a-z0-9-]+)+$").unwrap();
```
Comment (shane-tomlinson) [inline src/validate/mod.rs]: We should probably port this over to the content-server and auth-server validation too.
